M48
; DRILL file {KiCad (6.0.4-0)} date Monday, August 14, 2023 at 03:40:46 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-14T15:40:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.45Y1.4125
X0.45Y0.1625
X2.0Y1.4125
X2.0Y0.1625
T0
M30
